### PR TITLE
[WIP] i2c-hid: add

### LINKED ISSUE #58: Absolute positioned input device support
Currently RVVM support only relative-positioned PS/2 mouse emulation that require pointer capture. It is annoying and limiting because it do not work properly on touchscreens and tablets with digital pen. TinyEMU and QEmu supports absolute positioned pointer.

It can be implemented with i2c HID or USB HID.

### PR DESCRIPTION
**Pull request by X547**

### CODE REVIEW

File: src/devices/hid-keyboard.c [hunk 1]
```diff
@@ -0,0 +1,188 @@
...
+    0x19, 0x00,     /*   Usage Minimum (0) */
+    0x29, 0xff,     /*   Usage Maximum (255) */
+    0x81, 0x00,     /*   Input (Data, Array) */
+    0xc0,       /* End Collection */
+};
+
+struct hid_keyboard {
+    hid_dev_t hid_dev;
+    
+    uint32_t pad[1024];
```
Comment (LekKit) [inline src/devices/hid-keyboard.c]: What's this for? I see no more references to this, alignment sorta or debugging remnants?

File: src/devices/hid-keyboard.c [hunk 2]
```diff
@@ -0,0 +1,188 @@
...
+    spin_lock(&kb->lock);
+    switch (report_type) {
+    case REPORT_TYPE_INPUT:
+        if (offset == 0) {
+            kb->input_report[0] = bit_cut(sizeof(kb->input_report), 0, 8);
+            kb->input_report[1] = bit_cut(sizeof(kb->input_report), 8, 8);
+            kb->input_report[2] = bit_cut(kb->keys[7], 0, 8);
+            kb->input_report[3] = 0;
+            uint32_t idx = 0;
+            for (uint32_t code = 0; code < 256; code++) {
```
Comment (LekKit) [inline src/devices/hid-keyboard.c]: Is there a way to optimize this somehow? I.e. not loop over all buttons on report read, and buffer pressed keys in `hid_keyboard_press()`

Not a huge performance concern, but why not)

File: src/devices/hid-keyboard.c [hunk 3]
```diff
@@ -0,0 +1,188 @@
...
+        *val = 0;
+        break;
+    }
+    spin_unlock(&kb->lock);
+}
+
+static void hid_keyboard_write_report(void* dev,
+    uint8_t report_type, uint8_t report_id, uint32_t offset, uint8_t val)
+{
+    (void)report_id;
```
Comment (LekKit) [inline src/devices/hid-keyboard.c]: For clarity, write `UNUSED(var);` instead of `(void)var;`

File: src/devices/hid-mouse.c [hunk 4]
```diff
@@ -0,0 +1,225 @@
...
+        break;
+    }
+    spin_unlock(&mouse->lock);
+}
+
+static void hid_mouse_write_report(void* dev,
+    uint8_t report_type, uint8_t report_id, uint32_t offset, uint8_t val)
+{
+    hid_mouse_t* mouse = (hid_mouse_t*)dev;
+    (void)mouse;
```
Comment (LekKit) [inline src/devices/hid-mouse.c]: Same code style suggestion of `UNUSED(var);`

File: src/devices/hid_dev.h [hunk 5]
```diff
@@ -0,0 +1,44 @@
+#ifndef _HID_DEV_H_
```
Comment (LekKit) [inline src/devices/hid_dev.h]: Add GPL header, use `RVVM_HID_DEV_H` guard perhaps

File: src/devices/i2c-hid.h [hunk 6]
```diff
@@ -0,0 +1,27 @@
...
+along with this program.  If not, see <https://www.gnu.org/licenses/>.
+*/
+
+#ifndef _I2C_HID_H_
+#define _I2C_HID_H_
+
+#include "hid_dev.h"
+#include "rvvmlib.h"
+
+void i2c_hid_init(rvvm_machine_t* machine, hid_dev_t* hid_dev);
```
Comment (LekKit) [inline src/devices/i2c-hid.h]: Perhaps place `PUBLIC` attribute on this (On func body as well), if you want to allow librvvm users to add custom HID devices.

**Review by LekKit — COMMENTED** [review]
Pretty clean code, nice
I will now perform some automated testing on it (Sanitizers, fuzzing coverage)

**Comment by LekKit** [comment]
See https://lgtm.com/projects/g/LekKit/RVVM/rev/pr-b8a6a47c291229130d670c626dee7b8bd0c82b65 for automated code checks report, same warnings are seen when building with `make`.

File: src/devices/hid-keyboard.c (hunk 1 above)
Comment (X547) [reply src/devices/hid-keyboard.c]: Debug leftover. Removed.

**Comment by X547** [comment]
>

**Comment by X547** [comment]
> See https://lgtm.com/projects/g/LekKit/RVVM/rev/pr-b8a6a47c291229130d670c626dee7b8bd0c82b65 for automated code checks report, same warnings are seen when building with `make`.

I am not sure what to do with `key < 256` check. Removing check will cause memory corruption if more than 256 key codes will be added.

About undeclared `memset`: I think that some `-Werror` option should be used in make/cmake to avoid such issues.

**Comment by X547** [comment]
> LGTM.com will be shut down in December 2022 — we recommend that you use GitHub code scanning instead. Read more in [our blog post on the GitHub blog](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/).

**Comment by LekKit** [comment]
> About undeclared `memset`: I think that some `-Werror` option should be used in make/cmake to avoid such issues.

Compiling with `-Werror` is bad, we just enable ton of warnings and expect them to be fixed when you see them

**Comment by X547** [comment]
> > 
> 
> Compiling with `-Werror` is bad, we just enable ton of warnings and expect them to be fixed when you see them

`cmake` build do not show warning about `memset`.

**Comment by LekKit** [comment]
> I am not sure what to do with `key < 256` check. 

It is expected that hid_key_t is *always* 1 byte and there never will be more than 255 different keys, because it follows actual frozen HID standard.
I can add something like `HID_KEY_MAX` for that matter, because there aren't even that much keys now (less than 128 if memory serves)

**Comment by LekKit** [comment]
> > > 
> > 
> > 
> > Compiling with `-Werror` is bad, we just enable ton of warnings and expect them to be fixed when you see them
> 
> `cmake` build do not show warning about `memset`.

Weird, I'll look into that

**Comment by LekKit** [comment]
What would be a meaningful check though is `if (key != HID_KEY_NONE)`

**Comment by X547** [comment]
Do HID keyboard device need to record event history?

**Comment by LekKit** [comment]
> Do HID keyboard device need to record event history?

For key rollover or to prevent lost events if the guest is laggy?

**Comment by X547** [comment]
> For key rollover or to prevent lost events if the guest is laggy?

Second: to prevent lost events. PS/2 Keyboard use ring buffer.

**Comment by LekKit** [comment]
> > For key rollover or to prevent lost events if the guest is laggy?
> 
> Second: to prevent lost events. PS/2 Keyboard use ring buffer.

You may do that, ofc. Is there a way to report events quickly without looping, and if it fails read the whole buttons bitmask?

**Comment by X547** [comment]
> Is there a way to report events quickly without looping, and if it fails read the whole buttons bitmask?

Optimized a bit (skip 32 bits if uint32_t value is zero).

UPDATE: broken: `break` do not exit outer loop.

File: src/devices/hid-keyboard.c [hunk 7]
```diff
@@ -0,0 +1,193 @@
...
+    spin_lock(&kb->lock);
+    switch (report_type) {
+    case REPORT_TYPE_INPUT:
+        if (offset == 0) {
+            kb->input_report[0] = bit_cut(sizeof(kb->input_report), 0, 8);
+            kb->input_report[1] = bit_cut(sizeof(kb->input_report), 8, 8);
+            kb->input_report[2] = bit_cut(kb->keys[7], 0, 8);
+            kb->input_report[3] = 0;
+            uint32_t idx = 0;
+            for (uint32_t code_hi = 0; code_hi < 8; code_hi++) {
```
Comment (LekKit) [inline src/devices/hid-keyboard.c]: Oh, that's a fine idea

**Comment by LekKit** [comment]
```
src/devices/hid-keyboard.c:105:35: runtime error: left shift of 1 by 31 places cannot be represented in type 'int'
    #0 0x56264a552d5c in hid_keyboard_read_report /home/lekkit/stuff/RVVM/src/devices/hid-keyboard.c:105:35
    #1 0x56264a55d935 in i2c_hid_read_report /home/lekkit/stuff/RVVM/src/devices/i2c-hid.c:165:5
    #2 0x56264a55a66b in i2c_hid_read_reg /home/lekkit/stuff/RVVM/src/devices/i2c-hid.c:221:9
    #3 0x56264a55a66b in i2c_hid_read /home/lekkit/stuff/RVVM/src/devices/i2c-hid.c:317:13
    #4 0x56264a560492 in i2c_oc_mmio_write /home/lekkit/stuff/RVVM/src/devices/i2c-oc.c:163:32
    #5 0x56264a503342 in riscv_mmio_unaligned_op /home/lekkit/stuff/RVVM/src/main.c:83:12
    #6 0x56264a503306 in riscv_mmio_unaligned_op /home/lekkit/stuff/RVVM/src/main.c:81:16
    #7 0x56264a5027b2 in LLVMFuzzerTestOneInput /home/lekkit/stuff/RVVM/src/main.c:137:17
```

Upd: this is 06f7efc, use (1U << code_lo) for bitfield checks

**Comment by X547** [comment]
> Upd: this is [06f7efc](https://github.com/LekKit/RVVM/commit/06f7efca59d9d884a637d5a95cc01327b85472d6), use (1U << code_lo) for bitfield checks

Done.

**Comment by LekKit** [comment]
As for the ThreadSanitizer report though, it's huge...

<details>
  <summary>Oh, dataraces...</summary>

```
WARNING: ThreadSanitizer: data race (pid=191931)
  Read of size 1 at 0x7b54000009b8 by main thread:
    #0 i2c_hid_input_available.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:155:18 (rvvm_x86_64+0xfa375)
    #1 hid_mouse_place /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:222:9 (rvvm_x86_64+0xf95e1)
    #2 fb_window_update /home/lekkit/RVVM/RVVM/src/devices/x11window_xlib.c:377:17 (rvvm_x86_64+0x11c466)
    #3 window_update /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:80:5 (rvvm_x86_64+0xf7dff)
    #4 builtin_eventloop.llvm.889849392825762815 /home/lekkit/RVVM/RVVM/src/rvvm.c:255:21 (rvvm_x86_64+0xf4030)
    #5 rvvm_run_eventloop /home/lekkit/RVVM/RVVM/src/rvvm.c:701:5 (rvvm_x86_64+0xf51a3)
    #6 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:248:9 (rvvm_x86_64+0xea13a)
    #7 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea13a)

  Previous write of size 1 at 0x7b54000009b8 by thread T1:
    #0 i2c_hid_stop.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:328:23 (rvvm_x86_64+0xfa19e)
    #1 i2c_oc_mmio_write.llvm.12219271496437194821 /home/lekkit/RVVM/RVVM/src/devices/i2c-oc.c:171:47 (rvvm_x86_64+0xfae5a)
    #2 riscv_mmio_scan /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:403:20 (rvvm_x86_64+0xefe06)
    #3 riscv_mmu_op.llvm.11025864126483078052 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:471:13 (rvvm_x86_64+0xefe06)
    #4 riscv_mmu_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:680:5 (rvvm_x86_64+0xf06f8)
    #5 riscv_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.h:286:5 (rvvm_x86_64+0x139e49)
    #6 riscv_i_sb.llvm.17544518338265111532 /home/lekkit/RVVM/RVVM/src/cpu/riscv_i.c:352:5 (rvvm_x86_64+0x139e49)
    #7 riscv_emulate.llvm.288625106820532266 /home/lekkit/RVVM/RVVM/src/riscv_cpu.c:168:9 (rvvm_x86_64+0xeabca)
    #8 riscv_run_till_event /home/lekkit/RVVM/RVVM/src/riscv_cpu.c (rvvm_x86_64+0xeaaf1)
    #9 riscv_hart_run /home/lekkit/RVVM/RVVM/src/riscv_hart.c:95:9 (rvvm_x86_64+0xee837)
    #10 riscv_hart_run_wrap.llvm.8645139548926494406 /home/lekkit/RVVM/RVVM/src/riscv_hart.c:316:5 (rvvm_x86_64+0xee837)
    #11 __tsan_thread_start_func <null> (rvvm_x86_64+0x5f5f2)

  Location is heap block of size 576 at 0x7b5400000780 allocated by main thread:
    #0 calloc <null> (rvvm_x86_64+0x7e90b)
    #1 safe_calloc /home/lekkit/RVVM/RVVM/src/utils.c:99:17 (rvvm_x86_64+0xf96f0)
    #2 i2c_hid_init /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:349:26 (rvvm_x86_64+0xf96f0)
    #3 i2c_hid_init_auto /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:388:5 (rvvm_x86_64+0xf96f0)
    #4 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #5 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #6 fb_window_init_auto /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:127:21 (rvvm_x86_64+0xf7ced)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:222:14 (rvvm_x86_64+0xe9b09)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xe9b09)

  Thread T1 (tid=191935, running) created by main thread at:
    #0 pthread_create <null> (rvvm_x86_64+0x647f6)
    #1 thread_create /home/lekkit/RVVM/RVVM/src/threading.c:61:13 (rvvm_x86_64+0xee6f9)
    #2 riscv_hart_spawn /home/lekkit/RVVM/RVVM/src/riscv_hart.c:323:18 (rvvm_x86_64+0xee6f9)
    #3 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #4 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #5 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:247:9 (rvvm_x86_64+0xea135)
    #6 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea135)

SUMMARY: ThreadSanitizer: data race /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:155:18 in i2c_hid_input_available.llvm.1433193341291022662
==================
==================
WARNING: ThreadSanitizer: data race (pid=191931)
  Read of size 2 at 0x7b54000007a8 by main thread:
    #0 report_id_queue_insert /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:106:29 (rvvm_x86_64+0xfa392)
    #1 i2c_hid_input_available.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:156:5 (rvvm_x86_64+0xfa392)
    #2 hid_mouse_place /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:222:9 (rvvm_x86_64+0xf95e1)
    #3 fb_window_update /home/lekkit/RVVM/RVVM/src/devices/x11window_xlib.c:377:17 (rvvm_x86_64+0x11c466)
    #4 window_update /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:80:5 (rvvm_x86_64+0xf7dff)
    #5 builtin_eventloop.llvm.889849392825762815 /home/lekkit/RVVM/RVVM/src/rvvm.c:255:21 (rvvm_x86_64+0xf4030)
    #6 rvvm_run_eventloop /home/lekkit/RVVM/RVVM/src/rvvm.c:701:5 (rvvm_x86_64+0xf51a3)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:248:9 (rvvm_x86_64+0xea13a)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea13a)

  Previous write of size 2 at 0x7b54000007a8 by thread T1:
    #0 report_id_queue_remove_at /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:125:43 (rvvm_x86_64+0xfa575)
    #1 i2c_hid_read_report /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:169:9 (rvvm_x86_64+0xfa575)
    #2 i2c_hid_read_reg /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:221:9 (rvvm_x86_64+0xf9f41)
    #3 i2c_hid_read.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:317:13 (rvvm_x86_64+0xf9f41)
    #4 i2c_oc_mmio_write.llvm.12219271496437194821 /home/lekkit/RVVM/RVVM/src/devices/i2c-oc.c:163:32 (rvvm_x86_64+0xfad7e)
    #5 riscv_mmio_scan /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:403:20 (rvvm_x86_64+0xefe06)
    #6 riscv_mmu_op.llvm.11025864126483078052 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:471:13 (rvvm_x86_64+0xefe06)
    #7 riscv_mmu_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:680:5 (rvvm_x86_64+0xf06f8)
    #8 riscv_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.h:286:5 (rvvm_x86_64+0x139e49)
    #9 riscv_i_sb.llvm.17544518338265111532 /home/lekkit/RVVM/RVVM/src/cpu/riscv_i.c:352:5 (rvvm_x86_64+0x139e49)
    #10 riscv_emulate.llvm.288625106820532266 /home/lekkit/RVVM/RVVM/src/riscv_cpu.c:168:9 (rvvm_x86_64+0xeabca)
    #11 riscv_run_till_event /home/lekkit/RVVM/RVVM/src/riscv_cpu.c (rvvm_x86_64+0xeaaf1)
    #12 riscv_hart_run /home/lekkit/RVVM/RVVM/src/riscv_hart.c:95:9 (rvvm_x86_64+0xee837)
    #13 riscv_hart_run_wrap.llvm.8645139548926494406 /home/lekkit/RVVM/RVVM/src/riscv_hart.c:316:5 (rvvm_x86_64+0xee837)
    #14 __tsan_thread_start_func <null> (rvvm_x86_64+0x5f5f2)

  Location is heap block of size 576 at 0x7b5400000780 allocated by main thread:
    #0 calloc <null> (rvvm_x86_64+0x7e90b)
    #1 safe_calloc /home/lekkit/RVVM/RVVM/src/utils.c:99:17 (rvvm_x86_64+0xf96f0)
    #2 i2c_hid_init /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:349:26 (rvvm_x86_64+0xf96f0)
    #3 i2c_hid_init_auto /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:388:5 (rvvm_x86_64+0xf96f0)
    #4 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #5 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #6 fb_window_init_auto /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:127:21 (rvvm_x86_64+0xf7ced)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:222:14 (rvvm_x86_64+0xe9b09)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xe9b09)

  Thread T1 (tid=191935, running) created by main thread at:
    #0 pthread_create <null> (rvvm_x86_64+0x647f6)
    #1 thread_create /home/lekkit/RVVM/RVVM/src/threading.c:61:13 (rvvm_x86_64+0xee6f9)
    #2 riscv_hart_spawn /home/lekkit/RVVM/RVVM/src/riscv_hart.c:323:18 (rvvm_x86_64+0xee6f9)
    #3 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #4 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #5 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:247:9 (rvvm_x86_64+0xea135)
    #6 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea135)

SUMMARY: ThreadSanitizer: data race /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:106:29 in report_id_queue_insert
==================
==================
WARNING: ThreadSanitizer: data race (pid=191931)
  Read of size 2 at 0x7b54000007a6 by main thread:
    #0 report_id_queue_insert /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:108:16 (rvvm_x86_64+0xfa3c0)
    #1 i2c_hid_input_available.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:156:5 (rvvm_x86_64+0xfa3c0)
    #2 hid_mouse_place /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:222:9 (rvvm_x86_64+0xf95e1)
    #3 fb_window_update /home/lekkit/RVVM/RVVM/src/devices/x11window_xlib.c:377:17 (rvvm_x86_64+0x11c466)
    #4 window_update /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:80:5 (rvvm_x86_64+0xf7dff)
    #5 builtin_eventloop.llvm.889849392825762815 /home/lekkit/RVVM/RVVM/src/rvvm.c:255:21 (rvvm_x86_64+0xf4030)
    #6 rvvm_run_eventloop /home/lekkit/RVVM/RVVM/src/rvvm.c:701:5 (rvvm_x86_64+0xf51a3)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:248:9 (rvvm_x86_64+0xea13a)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea13a)

  Previous write of size 2 at 0x7b54000007a6 by thread T1:
    #0 report_id_queue_remove_at /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:124:22 (rvvm_x86_64+0xfa563)
    #1 i2c_hid_read_report /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:169:9 (rvvm_x86_64+0xfa563)
    #2 i2c_hid_read_reg /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:221:9 (rvvm_x86_64+0xf9f41)
    #3 i2c_hid_read.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:317:13 (rvvm_x86_64+0xf9f41)
    #4 i2c_oc_mmio_write.llvm.12219271496437194821 /home/lekkit/RVVM/RVVM/src/devices/i2c-oc.c:163:32 (rvvm_x86_64+0xfad7e)
    #5 riscv_mmio_scan /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:403:20 (rvvm_x86_64+0xefe06)
    #6 riscv_mmu_op.llvm.11025864126483078052 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:471:13 (rvvm_x86_64+0xefe06)
    #7 riscv_mmu_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:680:5 (rvvm_x86_64+0xf06f8)
    #8 riscv_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.h:286:5 (rvvm_x86_64+0x139e49)
    #9 riscv_i_sb.llvm.17544518338265111532 /home/lekkit/RVVM/RVVM/src/cpu/riscv_i.c:352:5 (rvvm_x86_64+0x139e49)
    #10 riscv_emulate.llvm.288625106820532266 /home/lekkit/RVVM/RVVM/src/riscv_cpu.c:168:9 (rvvm_x86_64+0xeabca)
    #11 riscv_run_till_event /home/lekkit/RVVM/RVVM/src/riscv_cpu.c (rvvm_x86_64+0xeaaf1)
    #12 riscv_hart_run /home/lekkit/RVVM/RVVM/src/riscv_hart.c:95:9 (rvvm_x86_64+0xee837)
    #13 riscv_hart_run_wrap.llvm.8645139548926494406 /home/lekkit/RVVM/RVVM/src/riscv_hart.c:316:5 (rvvm_x86_64+0xee837)
    #14 __tsan_thread_start_func <null> (rvvm_x86_64+0x5f5f2)

  Location is heap block of size 576 at 0x7b5400000780 allocated by main thread:
    #0 calloc <null> (rvvm_x86_64+0x7e90b)
    #1 safe_calloc /home/lekkit/RVVM/RVVM/src/utils.c:99:17 (rvvm_x86_64+0xf96f0)
    #2 i2c_hid_init /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:349:26 (rvvm_x86_64+0xf96f0)
    #3 i2c_hid_init_auto /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:388:5 (rvvm_x86_64+0xf96f0)
    #4 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #5 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #6 fb_window_init_auto /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:127:21 (rvvm_x86_64+0xf7ced)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:222:14 (rvvm_x86_64+0xe9b09)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xe9b09)

  Thread T1 (tid=191935, running) created by main thread at:
    #0 pthread_create <null> (rvvm_x86_64+0x647f6)
    #1 thread_create /home/lekkit/RVVM/RVVM/src/threading.c:61:13 (rvvm_x86_64+0xee6f9)
    #2 riscv_hart_spawn /home/lekkit/RVVM/RVVM/src/riscv_hart.c:323:18 (rvvm_x86_64+0xee6f9)
    #3 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #4 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #5 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:247:9 (rvvm_x86_64+0xea135)
    #6 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea135)

SUMMARY: ThreadSanitizer: data race /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:108:16 in report_id_queue_insert
==================
==================
WARNING: ThreadSanitizer: data race (pid=191931)
  Write of size 2 at 0x7b54000007a6 by main thread:
    #0 report_id_queue_insert /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c (rvvm_x86_64+0xfa3d6)
    #1 i2c_hid_input_available.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:156:5 (rvvm_x86_64+0xfa3d6)
    #2 hid_mouse_place /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:222:9 (rvvm_x86_64+0xf95e1)
    #3 fb_window_update /home/lekkit/RVVM/RVVM/src/devices/x11window_xlib.c:377:17 (rvvm_x86_64+0x11c466)
    #4 window_update /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:80:5 (rvvm_x86_64+0xf7dff)
    #5 builtin_eventloop.llvm.889849392825762815 /home/lekkit/RVVM/RVVM/src/rvvm.c:255:21 (rvvm_x86_64+0xf4030)
    #6 rvvm_run_eventloop /home/lekkit/RVVM/RVVM/src/rvvm.c:701:5 (rvvm_x86_64+0xf51a3)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:248:9 (rvvm_x86_64+0xea13a)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea13a)

  Previous write of size 2 at 0x7b54000007a6 by thread T1:
    #0 report_id_queue_remove_at /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:124:22 (rvvm_x86_64+0xfa563)
    #1 i2c_hid_read_report /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:169:9 (rvvm_x86_64+0xfa563)
    #2 i2c_hid_read_reg /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:221:9 (rvvm_x86_64+0xf9f41)
    #3 i2c_hid_read.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:317:13 (rvvm_x86_64+0xf9f41)
    #4 i2c_oc_mmio_write.llvm.12219271496437194821 /home/lekkit/RVVM/RVVM/src/devices/i2c-oc.c:163:32 (rvvm_x86_64+0xfad7e)
    #5 riscv_mmio_scan /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:403:20 (rvvm_x86_64+0xefe06)
    #6 riscv_mmu_op.llvm.11025864126483078052 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:471:13 (rvvm_x86_64+0xefe06)
    #7 riscv_mmu_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:680:5 (rvvm_x86_64+0xf06f8)
    #8 riscv_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.h:286:5 (rvvm_x86_64+0x139e49)
    #9 riscv_i_sb.llvm.17544518338265111532 /home/lekkit/RVVM/RVVM/src/cpu/riscv_i.c:352:5 (rvvm_x86_64+0x139e49)
    #10 riscv_emulate.llvm.288625106820532266 /home/lekkit/RVVM/RVVM/src/riscv_cpu.c:168:9 (rvvm_x86_64+0xeabca)
    #11 riscv_run_till_event /home/lekkit/RVVM/RVVM/src/riscv_cpu.c (rvvm_x86_64+0xeaaf1)
    #12 riscv_hart_run /home/lekkit/RVVM/RVVM/src/riscv_hart.c:95:9 (rvvm_x86_64+0xee837)
    #13 riscv_hart_run_wrap.llvm.8645139548926494406 /home/lekkit/RVVM/RVVM/src/riscv_hart.c:316:5 (rvvm_x86_64+0xee837)
    #14 __tsan_thread_start_func <null> (rvvm_x86_64+0x5f5f2)

  Location is heap block of size 576 at 0x7b5400000780 allocated by main thread:
    #0 calloc <null> (rvvm_x86_64+0x7e90b)
    #1 safe_calloc /home/lekkit/RVVM/RVVM/src/utils.c:99:17 (rvvm_x86_64+0xf96f0)
    #2 i2c_hid_init /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:349:26 (rvvm_x86_64+0xf96f0)
    #3 i2c_hid_init_auto /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:388:5 (rvvm_x86_64+0xf96f0)
    #4 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #5 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #6 fb_window_init_auto /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:127:21 (rvvm_x86_64+0xf7ced)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:222:14 (rvvm_x86_64+0xe9b09)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xe9b09)

  Thread T1 (tid=191935, running) created by main thread at:
    #0 pthread_create <null> (rvvm_x86_64+0x647f6)
    #1 thread_create /home/lekkit/RVVM/RVVM/src/threading.c:61:13 (rvvm_x86_64+0xee6f9)
    #2 riscv_hart_spawn /home/lekkit/RVVM/RVVM/src/riscv_hart.c:323:18 (rvvm_x86_64+0xee6f9)
    #3 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #4 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #5 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:247:9 (rvvm_x86_64+0xea135)
    #6 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea135)

SUMMARY: ThreadSanitizer: data race /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c in report_id_queue_insert
==================
==================
WARNING: ThreadSanitizer: data race (pid=191931)
  Write of size 2 at 0x7b54000007a8 by main thread:
    #0 report_id_queue_insert /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:112:17 (rvvm_x86_64+0xfa3e3)
    #1 i2c_hid_input_available.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:156:5 (rvvm_x86_64+0xfa3e3)
    #2 hid_mouse_place /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:222:9 (rvvm_x86_64+0xf95e1)
    #3 fb_window_update /home/lekkit/RVVM/RVVM/src/devices/x11window_xlib.c:377:17 (rvvm_x86_64+0x11c466)
    #4 window_update /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:80:5 (rvvm_x86_64+0xf7dff)
    #5 builtin_eventloop.llvm.889849392825762815 /home/lekkit/RVVM/RVVM/src/rvvm.c:255:21 (rvvm_x86_64+0xf4030)
    #6 rvvm_run_eventloop /home/lekkit/RVVM/RVVM/src/rvvm.c:701:5 (rvvm_x86_64+0xf51a3)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:248:9 (rvvm_x86_64+0xea13a)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea13a)

  Previous write of size 2 at 0x7b54000007a8 by thread T1:
    #0 report_id_queue_remove_at /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:125:43 (rvvm_x86_64+0xfa575)
    #1 i2c_hid_read_report /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:169:9 (rvvm_x86_64+0xfa575)
    #2 i2c_hid_read_reg /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:221:9 (rvvm_x86_64+0xf9f41)
    #3 i2c_hid_read.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:317:13 (rvvm_x86_64+0xf9f41)
    #4 i2c_oc_mmio_write.llvm.12219271496437194821 /home/lekkit/RVVM/RVVM/src/devices/i2c-oc.c:163:32 (rvvm_x86_64+0xfad7e)
    #5 riscv_mmio_scan /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:403:20 (rvvm_x86_64+0xefe06)
    #6 riscv_mmu_op.llvm.11025864126483078052 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:471:13 (rvvm_x86_64+0xefe06)
    #7 riscv_mmu_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:680:5 (rvvm_x86_64+0xf06f8)
    #8 riscv_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.h:286:5 (rvvm_x86_64+0x139e49)
    #9 riscv_i_sb.llvm.17544518338265111532 /home/lekkit/RVVM/RVVM/src/cpu/riscv_i.c:352:5 (rvvm_x86_64+0x139e49)
    #10 riscv_emulate.llvm.288625106820532266 /home/lekkit/RVVM/RVVM/src/riscv_cpu.c:168:9 (rvvm_x86_64+0xeabca)
    #11 riscv_run_till_event /home/lekkit/RVVM/RVVM/src/riscv_cpu.c (rvvm_x86_64+0xeaaf1)
    #12 riscv_hart_run /home/lekkit/RVVM/RVVM/src/riscv_hart.c:95:9 (rvvm_x86_64+0xee837)
    #13 riscv_hart_run_wrap.llvm.8645139548926494406 /home/lekkit/RVVM/RVVM/src/riscv_hart.c:316:5 (rvvm_x86_64+0xee837)
    #14 __tsan_thread_start_func <null> (rvvm_x86_64+0x5f5f2)

  Location is heap block of size 576 at 0x7b5400000780 allocated by main thread:
    #0 calloc <null> (rvvm_x86_64+0x7e90b)
    #1 safe_calloc /home/lekkit/RVVM/RVVM/src/utils.c:99:17 (rvvm_x86_64+0xf96f0)
    #2 i2c_hid_init /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:349:26 (rvvm_x86_64+0xf96f0)
    #3 i2c_hid_init_auto /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:388:5 (rvvm_x86_64+0xf96f0)
    #4 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #5 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #6 fb_window_init_auto /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:127:21 (rvvm_x86_64+0xf7ced)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:222:14 (rvvm_x86_64+0xe9b09)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xe9b09)

  Thread T1 (tid=191935, running) created by main thread at:
    #0 pthread_create <null> (rvvm_x86_64+0x647f6)
    #1 thread_create /home/lekkit/RVVM/RVVM/src/threading.c:61:13 (rvvm_x86_64+0xee6f9)
    #2 riscv_hart_spawn /home/lekkit/RVVM/RVVM/src/riscv_hart.c:323:18 (rvvm_x86_64+0xee6f9)
    #3 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #4 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #5 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:247:9 (rvvm_x86_64+0xea135)
    #6 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea135)

SUMMARY: ThreadSanitizer: data race /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:112:17 in report_id_queue_insert
==================
==================
WARNING: ThreadSanitizer: data race (pid=191931)
  Read of size 2 at 0x7b54000007a8 by main thread:
    #0 report_id_queue_insert /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:106:29 (rvvm_x86_64+0xfa392)
    #1 i2c_hid_input_available.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:156:5 (rvvm_x86_64+0xfa392)
    #2 hid_mouse_scroll /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:185:5 (rvvm_x86_64+0xf9388)
    #3 fb_window_update /home/lekkit/RVVM/RVVM/src/devices/x11window_xlib.c:364:21 (rvvm_x86_64+0x11c63f)
    #4 window_update /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:80:5 (rvvm_x86_64+0xf7dff)
    #5 builtin_eventloop.llvm.889849392825762815 /home/lekkit/RVVM/RVVM/src/rvvm.c:255:21 (rvvm_x86_64+0xf4030)
    #6 rvvm_run_eventloop /home/lekkit/RVVM/RVVM/src/rvvm.c:701:5 (rvvm_x86_64+0xf51a3)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:248:9 (rvvm_x86_64+0xea13a)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea13a)

  Previous write of size 2 at 0x7b54000007a8 by thread T1:
    #0 report_id_queue_remove_at /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:125:43 (rvvm_x86_64+0xfa575)
    #1 i2c_hid_read_report /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:169:9 (rvvm_x86_64+0xfa575)
    #2 i2c_hid_read_reg /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:221:9 (rvvm_x86_64+0xf9f41)
    #3 i2c_hid_read.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:317:13 (rvvm_x86_64+0xf9f41)
    #4 i2c_oc_mmio_write.llvm.12219271496437194821 /home/lekkit/RVVM/RVVM/src/devices/i2c-oc.c:163:32 (rvvm_x86_64+0xfad7e)
    #5 riscv_mmio_scan /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:403:20 (rvvm_x86_64+0xefe06)
    #6 riscv_mmu_op.llvm.11025864126483078052 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:471:13 (rvvm_x86_64+0xefe06)
    #7 riscv_mmu_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:680:5 (rvvm_x86_64+0xf06f8)
    #8 riscv_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.h:286:5 (rvvm_x86_64+0x139e49)
    #9 riscv_i_sb.llvm.17544518338265111532 /home/lekkit/RVVM/RVVM/src/cpu/riscv_i.c:352:5 (rvvm_x86_64+0x139e49)
    #10 riscv_emulate.llvm.288625106820532266 /home/lekkit/RVVM/RVVM/src/riscv_cpu.c:168:9 (rvvm_x86_64+0xeabca)
    #11 riscv_run_till_event /home/lekkit/RVVM/RVVM/src/riscv_cpu.c (rvvm_x86_64+0xeaaf1)
    #12 riscv_hart_run /home/lekkit/RVVM/RVVM/src/riscv_hart.c:95:9 (rvvm_x86_64+0xee837)
    #13 riscv_hart_run_wrap.llvm.8645139548926494406 /home/lekkit/RVVM/RVVM/src/riscv_hart.c:316:5 (rvvm_x86_64+0xee837)
    #14 __tsan_thread_start_func <null> (rvvm_x86_64+0x5f5f2)

  Location is heap block of size 576 at 0x7b5400000780 allocated by main thread:
    #0 calloc <null> (rvvm_x86_64+0x7e90b)
    #1 safe_calloc /home/lekkit/RVVM/RVVM/src/utils.c:99:17 (rvvm_x86_64+0xf96f0)
    #2 i2c_hid_init /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:349:26 (rvvm_x86_64+0xf96f0)
    #3 i2c_hid_init_auto /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:388:5 (rvvm_x86_64+0xf96f0)
    #4 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #5 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #6 fb_window_init_auto /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:127:21 (rvvm_x86_64+0xf7ced)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:222:14 (rvvm_x86_64+0xe9b09)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xe9b09)

  Thread T1 (tid=191935, running) created by main thread at:
    #0 pthread_create <null> (rvvm_x86_64+0x647f6)
    #1 thread_create /home/lekkit/RVVM/RVVM/src/threading.c:61:13 (rvvm_x86_64+0xee6f9)
    #2 riscv_hart_spawn /home/lekkit/RVVM/RVVM/src/riscv_hart.c:323:18 (rvvm_x86_64+0xee6f9)
    #3 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #4 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #5 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:247:9 (rvvm_x86_64+0xea135)
    #6 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea135)

SUMMARY: ThreadSanitizer: data race /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:106:29 in report_id_queue_insert
==================
==================
WARNING: ThreadSanitizer: data race (pid=191931)
  Read of size 2 at 0x7b54000007a6 by main thread:
    #0 report_id_queue_insert /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:108:16 (rvvm_x86_64+0xfa3c0)
    #1 i2c_hid_input_available.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:156:5 (rvvm_x86_64+0xfa3c0)
    #2 hid_mouse_scroll /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:185:5 (rvvm_x86_64+0xf9388)
    #3 fb_window_update /home/lekkit/RVVM/RVVM/src/devices/x11window_xlib.c:364:21 (rvvm_x86_64+0x11c63f)
    #4 window_update /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:80:5 (rvvm_x86_64+0xf7dff)
    #5 builtin_eventloop.llvm.889849392825762815 /home/lekkit/RVVM/RVVM/src/rvvm.c:255:21 (rvvm_x86_64+0xf4030)
    #6 rvvm_run_eventloop /home/lekkit/RVVM/RVVM/src/rvvm.c:701:5 (rvvm_x86_64+0xf51a3)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:248:9 (rvvm_x86_64+0xea13a)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea13a)

  Previous write of size 2 at 0x7b54000007a6 by thread T1:
    #0 report_id_queue_remove_at /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:124:22 (rvvm_x86_64+0xfa563)
    #1 i2c_hid_read_report /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:169:9 (rvvm_x86_64+0xfa563)
    #2 i2c_hid_read_reg /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:221:9 (rvvm_x86_64+0xf9f41)
    #3 i2c_hid_read.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:317:13 (rvvm_x86_64+0xf9f41)
    #4 i2c_oc_mmio_write.llvm.12219271496437194821 /home/lekkit/RVVM/RVVM/src/devices/i2c-oc.c:163:32 (rvvm_x86_64+0xfad7e)
    #5 riscv_mmio_scan /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:403:20 (rvvm_x86_64+0xefe06)
    #6 riscv_mmu_op.llvm.11025864126483078052 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:471:13 (rvvm_x86_64+0xefe06)
    #7 riscv_mmu_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:680:5 (rvvm_x86_64+0xf06f8)
    #8 riscv_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.h:286:5 (rvvm_x86_64+0x139e49)
    #9 riscv_i_sb.llvm.17544518338265111532 /home/lekkit/RVVM/RVVM/src/cpu/riscv_i.c:352:5 (rvvm_x86_64+0x139e49)
    #10 riscv_emulate.llvm.288625106820532266 /home/lekkit/RVVM/RVVM/src/riscv_cpu.c:168:9 (rvvm_x86_64+0xeabca)
    #11 riscv_run_till_event /home/lekkit/RVVM/RVVM/src/riscv_cpu.c (rvvm_x86_64+0xeaaf1)
    #12 riscv_hart_run /home/lekkit/RVVM/RVVM/src/riscv_hart.c:95:9 (rvvm_x86_64+0xee837)
    #13 riscv_hart_run_wrap.llvm.8645139548926494406 /home/lekkit/RVVM/RVVM/src/riscv_hart.c:316:5 (rvvm_x86_64+0xee837)
    #14 __tsan_thread_start_func <null> (rvvm_x86_64+0x5f5f2)

  Location is heap block of size 576 at 0x7b5400000780 allocated by main thread:
    #0 calloc <null> (rvvm_x86_64+0x7e90b)
    #1 safe_calloc /home/lekkit/RVVM/RVVM/src/utils.c:99:17 (rvvm_x86_64+0xf96f0)
    #2 i2c_hid_init /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:349:26 (rvvm_x86_64+0xf96f0)
    #3 i2c_hid_init_auto /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:388:5 (rvvm_x86_64+0xf96f0)
    #4 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #5 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #6 fb_window_init_auto /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:127:21 (rvvm_x86_64+0xf7ced)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:222:14 (rvvm_x86_64+0xe9b09)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xe9b09)

  Thread T1 (tid=191935, running) created by main thread at:
    #0 pthread_create <null> (rvvm_x86_64+0x647f6)
    #1 thread_create /home/lekkit/RVVM/RVVM/src/threading.c:61:13 (rvvm_x86_64+0xee6f9)
    #2 riscv_hart_spawn /home/lekkit/RVVM/RVVM/src/riscv_hart.c:323:18 (rvvm_x86_64+0xee6f9)
    #3 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #4 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #5 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:247:9 (rvvm_x86_64+0xea135)
    #6 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea135)

SUMMARY: ThreadSanitizer: data race /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:108:16 in report_id_queue_insert
==================
==================
WARNING: ThreadSanitizer: data race (pid=191931)
  Write of size 2 at 0x7b54000007a8 by main thread:
    #0 report_id_queue_insert /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:112:17 (rvvm_x86_64+0xfa3e3)
    #1 i2c_hid_input_available.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:156:5 (rvvm_x86_64+0xfa3e3)
    #2 hid_mouse_scroll /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:185:5 (rvvm_x86_64+0xf9388)
    #3 fb_window_update /home/lekkit/RVVM/RVVM/src/devices/x11window_xlib.c:364:21 (rvvm_x86_64+0x11c63f)
    #4 window_update /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:80:5 (rvvm_x86_64+0xf7dff)
    #5 builtin_eventloop.llvm.889849392825762815 /home/lekkit/RVVM/RVVM/src/rvvm.c:255:21 (rvvm_x86_64+0xf4030)
    #6 rvvm_run_eventloop /home/lekkit/RVVM/RVVM/src/rvvm.c:701:5 (rvvm_x86_64+0xf51a3)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:248:9 (rvvm_x86_64+0xea13a)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea13a)

  Previous write of size 2 at 0x7b54000007a8 by thread T1:
    #0 report_id_queue_remove_at /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:125:43 (rvvm_x86_64+0xfa575)
    #1 i2c_hid_read_report /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:169:9 (rvvm_x86_64+0xfa575)
    #2 i2c_hid_read_reg /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:221:9 (rvvm_x86_64+0xf9f41)
    #3 i2c_hid_read.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:317:13 (rvvm_x86_64+0xf9f41)
    #4 i2c_oc_mmio_write.llvm.12219271496437194821 /home/lekkit/RVVM/RVVM/src/devices/i2c-oc.c:163:32 (rvvm_x86_64+0xfad7e)
    #5 riscv_mmio_scan /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:403:20 (rvvm_x86_64+0xefe06)
    #6 riscv_mmu_op.llvm.11025864126483078052 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:471:13 (rvvm_x86_64+0xefe06)
    #7 riscv_mmu_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:680:5 (rvvm_x86_64+0xf06f8)
    #8 riscv_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.h:286:5 (rvvm_x86_64+0x139e49)
    #9 riscv_i_sb.llvm.17544518338265111532 /home/lekkit/RVVM/RVVM/src/cpu/riscv_i.c:352:5 (rvvm_x86_64+0x139e49)
    #10 riscv_emulate.llvm.288625106820532266 /home/lekkit/RVVM/RVVM/src/riscv_cpu.c:168:9 (rvvm_x86_64+0xeabca)
    #11 riscv_run_till_event /home/lekkit/RVVM/RVVM/src/riscv_cpu.c (rvvm_x86_64+0xeaaf1)
    #12 riscv_hart_run /home/lekkit/RVVM/RVVM/src/riscv_hart.c:95:9 (rvvm_x86_64+0xee837)
    #13 riscv_hart_run_wrap.llvm.8645139548926494406 /home/lekkit/RVVM/RVVM/src/riscv_hart.c:316:5 (rvvm_x86_64+0xee837)
    #14 __tsan_thread_start_func <null> (rvvm_x86_64+0x5f5f2)

  Location is heap block of size 576 at 0x7b5400000780 allocated by main thread:
    #0 calloc <null> (rvvm_x86_64+0x7e90b)
    #1 safe_calloc /home/lekkit/RVVM/RVVM/src/utils.c:99:17 (rvvm_x86_64+0xf96f0)
    #2 i2c_hid_init /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:349:26 (rvvm_x86_64+0xf96f0)
    #3 i2c_hid_init_auto /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:388:5 (rvvm_x86_64+0xf96f0)
    #4 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #5 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #6 fb_window_init_auto /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:127:21 (rvvm_x86_64+0xf7ced)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:222:14 (rvvm_x86_64+0xe9b09)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xe9b09)

  Thread T1 (tid=191935, running) created by main thread at:
    #0 pthread_create <null> (rvvm_x86_64+0x647f6)
    #1 thread_create /home/lekkit/RVVM/RVVM/src/threading.c:61:13 (rvvm_x86_64+0xee6f9)
    #2 riscv_hart_spawn /home/lekkit/RVVM/RVVM/src/riscv_hart.c:323:18 (rvvm_x86_64+0xee6f9)
    #3 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #4 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #5 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:247:9 (rvvm_x86_64+0xea135)
    #6 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea135)

SUMMARY: ThreadSanitizer: data race /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:112:17 in report_id_queue_insert
==================
==================
WARNING: ThreadSanitizer: data race (pid=191931)
  Write of size 1 at 0x7b54000007a4 by main thread:
    #0 i2c_hid_input_available.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:158:30 (rvvm_x86_64+0xfa401)
    #1 hid_mouse_scroll /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:185:5 (rvvm_x86_64+0xf9388)
    #2 fb_window_update /home/lekkit/RVVM/RVVM/src/devices/x11window_xlib.c:364:21 (rvvm_x86_64+0x11c63f)
    #3 window_update /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:80:5 (rvvm_x86_64+0xf7dff)
    #4 builtin_eventloop.llvm.889849392825762815 /home/lekkit/RVVM/RVVM/src/rvvm.c:255:21 (rvvm_x86_64+0xf4030)
    #5 rvvm_run_eventloop /home/lekkit/RVVM/RVVM/src/rvvm.c:701:5 (rvvm_x86_64+0xf51a3)
    #6 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:248:9 (rvvm_x86_64+0xea13a)
    #7 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea13a)

  Previous write of size 1 at 0x7b54000007a4 by thread T1:
    #0 i2c_hid_read_report /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:173:34 (rvvm_x86_64+0xfa608)
    #1 i2c_hid_read_reg /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:221:9 (rvvm_x86_64+0xf9f41)
    #2 i2c_hid_read.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:317:13 (rvvm_x86_64+0xf9f41)
    #3 i2c_oc_mmio_write.llvm.12219271496437194821 /home/lekkit/RVVM/RVVM/src/devices/i2c-oc.c:163:32 (rvvm_x86_64+0xfad7e)
    #4 riscv_mmio_scan /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:403:20 (rvvm_x86_64+0xefe06)
    #5 riscv_mmu_op.llvm.11025864126483078052 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:471:13 (rvvm_x86_64+0xefe06)
    #6 riscv_mmu_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:680:5 (rvvm_x86_64+0xf06f8)
    #7 riscv_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.h:286:5 (rvvm_x86_64+0x139e49)
    #8 riscv_i_sb.llvm.17544518338265111532 /home/lekkit/RVVM/RVVM/src/cpu/riscv_i.c:352:5 (rvvm_x86_64+0x139e49)
    #9 riscv_emulate.llvm.288625106820532266 /home/lekkit/RVVM/RVVM/src/riscv_cpu.c:168:9 (rvvm_x86_64+0xeabca)
    #10 riscv_run_till_event /home/lekkit/RVVM/RVVM/src/riscv_cpu.c (rvvm_x86_64+0xeaaf1)
    #11 riscv_hart_run /home/lekkit/RVVM/RVVM/src/riscv_hart.c:95:9 (rvvm_x86_64+0xee837)
    #12 riscv_hart_run_wrap.llvm.8645139548926494406 /home/lekkit/RVVM/RVVM/src/riscv_hart.c:316:5 (rvvm_x86_64+0xee837)
    #13 __tsan_thread_start_func <null> (rvvm_x86_64+0x5f5f2)

  Location is heap block of size 576 at 0x7b5400000780 allocated by main thread:
    #0 calloc <null> (rvvm_x86_64+0x7e90b)
    #1 safe_calloc /home/lekkit/RVVM/RVVM/src/utils.c:99:17 (rvvm_x86_64+0xf96f0)
    #2 i2c_hid_init /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:349:26 (rvvm_x86_64+0xf96f0)
    #3 i2c_hid_init_auto /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:388:5 (rvvm_x86_64+0xf96f0)
    #4 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #5 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #6 fb_window_init_auto /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:127:21 (rvvm_x86_64+0xf7ced)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:222:14 (rvvm_x86_64+0xe9b09)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xe9b09)

  Thread T1 (tid=191935, running) created by main thread at:
    #0 pthread_create <null> (rvvm_x86_64+0x647f6)
    #1 thread_create /home/lekkit/RVVM/RVVM/src/threading.c:61:13 (rvvm_x86_64+0xee6f9)
    #2 riscv_hart_spawn /home/lekkit/RVVM/RVVM/src/riscv_hart.c:323:18 (rvvm_x86_64+0xee6f9)
    #3 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #4 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #5 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:247:9 (rvvm_x86_64+0xea135)
    #6 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea135)

SUMMARY: ThreadSanitizer: data race /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:158:30 in i2c_hid_input_available.llvm.1433193341291022662
==================
==================
WARNING: ThreadSanitizer: data race (pid=191931)
  Write of size 2 at 0x7b54000007a6 by main thread:
    #0 report_id_queue_insert /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c (rvvm_x86_64+0xfa3d6)
    #1 i2c_hid_input_available.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:156:5 (rvvm_x86_64+0xfa3d6)
    #2 hid_mouse_scroll /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:185:5 (rvvm_x86_64+0xf9388)
    #3 fb_window_update /home/lekkit/RVVM/RVVM/src/devices/x11window_xlib.c:364:21 (rvvm_x86_64+0x11c63f)
    #4 window_update /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:80:5 (rvvm_x86_64+0xf7dff)
    #5 builtin_eventloop.llvm.889849392825762815 /home/lekkit/RVVM/RVVM/src/rvvm.c:255:21 (rvvm_x86_64+0xf4030)
    #6 rvvm_run_eventloop /home/lekkit/RVVM/RVVM/src/rvvm.c:701:5 (rvvm_x86_64+0xf51a3)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:248:9 (rvvm_x86_64+0xea13a)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea13a)

  Previous write of size 2 at 0x7b54000007a6 by thread T1:
    #0 report_id_queue_remove_at /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:124:22 (rvvm_x86_64+0xfa563)
    #1 i2c_hid_read_report /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:169:9 (rvvm_x86_64+0xfa563)
    #2 i2c_hid_read_reg /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:221:9 (rvvm_x86_64+0xf9f41)
    #3 i2c_hid_read.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:317:13 (rvvm_x86_64+0xf9f41)
    #4 i2c_oc_mmio_write.llvm.12219271496437194821 /home/lekkit/RVVM/RVVM/src/devices/i2c-oc.c:163:32 (rvvm_x86_64+0xfad7e)
    #5 riscv_mmio_scan /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:403:20 (rvvm_x86_64+0xefe06)
    #6 riscv_mmu_op.llvm.11025864126483078052 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:471:13 (rvvm_x86_64+0xefe06)
    #7 riscv_mmu_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:680:5 (rvvm_x86_64+0xf06f8)
    #8 riscv_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.h:286:5 (rvvm_x86_64+0x139e49)
    #9 riscv_i_sb.llvm.17544518338265111532 /home/lekkit/RVVM/RVVM/src/cpu/riscv_i.c:352:5 (rvvm_x86_64+0x139e49)
    #10 riscv_emulate.llvm.288625106820532266 /home/lekkit/RVVM/RVVM/src/riscv_cpu.c:168:9 (rvvm_x86_64+0xeabca)
    #11 riscv_run_till_event /home/lekkit/RVVM/RVVM/src/riscv_cpu.c (rvvm_x86_64+0xeaaf1)
    #12 riscv_hart_run /home/lekkit/RVVM/RVVM/src/riscv_hart.c:95:9 (rvvm_x86_64+0xee837)
    #13 riscv_hart_run_wrap.llvm.8645139548926494406 /home/lekkit/RVVM/RVVM/src/riscv_hart.c:316:5 (rvvm_x86_64+0xee837)
    #14 __tsan_thread_start_func <null> (rvvm_x86_64+0x5f5f2)

  Location is heap block of size 576 at 0x7b5400000780 allocated by main thread:
    #0 calloc <null> (rvvm_x86_64+0x7e90b)
    #1 safe_calloc /home/lekkit/RVVM/RVVM/src/utils.c:99:17 (rvvm_x86_64+0xf96f0)
    #2 i2c_hid_init /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:349:26 (rvvm_x86_64+0xf96f0)
    #3 i2c_hid_init_auto /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:388:5 (rvvm_x86_64+0xf96f0)
    #4 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #5 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #6 fb_window_init_auto /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:127:21 (rvvm_x86_64+0xf7ced)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:222:14 (rvvm_x86_64+0xe9b09)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xe9b09)

  Thread T1 (tid=191935, running) created by main thread at:
    #0 pthread_create <null> (rvvm_x86_64+0x647f6)
    #1 thread_create /home/lekkit/RVVM/RVVM/src/threading.c:61:13 (rvvm_x86_64+0xee6f9)
    #2 riscv_hart_spawn /home/lekkit/RVVM/RVVM/src/riscv_hart.c:323:18 (rvvm_x86_64+0xee6f9)
    #3 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #4 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #5 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:247:9 (rvvm_x86_64+0xea135)
    #6 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea135)

SUMMARY: ThreadSanitizer: data race /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c in report_id_queue_insert
==================
==================
WARNING: ThreadSanitizer: data race (pid=191931)
  Read of size 1 at 0x7b54000009b8 by main thread:
    #0 i2c_hid_input_available.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:155:18 (rvvm_x86_64+0xfa375)
    #1 hid_mouse_scroll /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:185:5 (rvvm_x86_64+0xf9388)
    #2 fb_window_update /home/lekkit/RVVM/RVVM/src/devices/x11window_xlib.c:364:21 (rvvm_x86_64+0x11c63f)
    #3 window_update /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:80:5 (rvvm_x86_64+0xf7dff)
    #4 builtin_eventloop.llvm.889849392825762815 /home/lekkit/RVVM/RVVM/src/rvvm.c:255:21 (rvvm_x86_64+0xf4030)
    #5 rvvm_run_eventloop /home/lekkit/RVVM/RVVM/src/rvvm.c:701:5 (rvvm_x86_64+0xf51a3)
    #6 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:248:9 (rvvm_x86_64+0xea13a)
    #7 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea13a)

  Previous write of size 1 at 0x7b54000009b8 by thread T1:
    #0 i2c_hid_stop.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:328:23 (rvvm_x86_64+0xfa19e)
    #1 i2c_oc_mmio_write.llvm.12219271496437194821 /home/lekkit/RVVM/RVVM/src/devices/i2c-oc.c:171:47 (rvvm_x86_64+0xfae5a)
    #2 riscv_mmio_scan /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:403:20 (rvvm_x86_64+0xefe06)
    #3 riscv_mmu_op.llvm.11025864126483078052 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:471:13 (rvvm_x86_64+0xefe06)
    #4 riscv_mmu_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:680:5 (rvvm_x86_64+0xf06f8)
    #5 riscv_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.h:286:5 (rvvm_x86_64+0x139e49)
    #6 riscv_i_sb.llvm.17544518338265111532 /home/lekkit/RVVM/RVVM/src/cpu/riscv_i.c:352:5 (rvvm_x86_64+0x139e49)
    #7 riscv_emulate.llvm.288625106820532266 /home/lekkit/RVVM/RVVM/src/riscv_cpu.c:168:9 (rvvm_x86_64+0xeabca)
    #8 riscv_run_till_event /home/lekkit/RVVM/RVVM/src/riscv_cpu.c (rvvm_x86_64+0xeaaf1)
    #9 riscv_hart_run /home/lekkit/RVVM/RVVM/src/riscv_hart.c:95:9 (rvvm_x86_64+0xee837)
    #10 riscv_hart_run_wrap.llvm.8645139548926494406 /home/lekkit/RVVM/RVVM/src/riscv_hart.c:316:5 (rvvm_x86_64+0xee837)
    #11 __tsan_thread_start_func <null> (rvvm_x86_64+0x5f5f2)

  Location is heap block of size 576 at 0x7b5400000780 allocated by main thread:
    #0 calloc <null> (rvvm_x86_64+0x7e90b)
    #1 safe_calloc /home/lekkit/RVVM/RVVM/src/utils.c:99:17 (rvvm_x86_64+0xf96f0)
    #2 i2c_hid_init /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:349:26 (rvvm_x86_64+0xf96f0)
    #3 i2c_hid_init_auto /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:388:5 (rvvm_x86_64+0xf96f0)
    #4 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #5 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #6 fb_window_init_auto /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:127:21 (rvvm_x86_64+0xf7ced)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:222:14 (rvvm_x86_64+0xe9b09)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xe9b09)

  Thread T1 (tid=191935, running) created by main thread at:
    #0 pthread_create <null> (rvvm_x86_64+0x647f6)
    #1 thread_create /home/lekkit/RVVM/RVVM/src/threading.c:61:13 (rvvm_x86_64+0xee6f9)
    #2 riscv_hart_spawn /home/lekkit/RVVM/RVVM/src/riscv_hart.c:323:18 (rvvm_x86_64+0xee6f9)
    #3 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #4 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #5 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:247:9 (rvvm_x86_64+0xea135)
    #6 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea135)

SUMMARY: ThreadSanitizer: data race /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:155:18 in i2c_hid_input_available.llvm.1433193341291022662
==================
==================
WARNING: ThreadSanitizer: data race (pid=191931)
  Read of size 2 at 0x7b54000007a8 by main thread:
    #0 report_id_queue_insert /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:106:29 (rvvm_x86_64+0xfa392)
    #1 i2c_hid_input_available.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:156:5 (rvvm_x86_64+0xfa392)
    #2 hid_mouse_scroll /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:185:5 (rvvm_x86_64+0xf9388)
    #3 fb_window_update /home/lekkit/RVVM/RVVM/src/devices/x11window_xlib.c:362:21 (rvvm_x86_64+0x11c620)
    #4 window_update /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:80:5 (rvvm_x86_64+0xf7dff)
    #5 builtin_eventloop.llvm.889849392825762815 /home/lekkit/RVVM/RVVM/src/rvvm.c:255:21 (rvvm_x86_64+0xf4030)
    #6 rvvm_run_eventloop /home/lekkit/RVVM/RVVM/src/rvvm.c:701:5 (rvvm_x86_64+0xf51a3)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:248:9 (rvvm_x86_64+0xea13a)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea13a)

  Previous write of size 2 at 0x7b54000007a8 by thread T1:
    #0 report_id_queue_remove_at /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:125:43 (rvvm_x86_64+0xfa575)
    #1 i2c_hid_read_report /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:169:9 (rvvm_x86_64+0xfa575)
    #2 i2c_hid_read_reg /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:221:9 (rvvm_x86_64+0xf9f41)
    #3 i2c_hid_read.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:317:13 (rvvm_x86_64+0xf9f41)
    #4 i2c_oc_mmio_write.llvm.12219271496437194821 /home/lekkit/RVVM/RVVM/src/devices/i2c-oc.c:163:32 (rvvm_x86_64+0xfad7e)
    #5 riscv_mmio_scan /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:403:20 (rvvm_x86_64+0xefe06)
    #6 riscv_mmu_op.llvm.11025864126483078052 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:471:13 (rvvm_x86_64+0xefe06)
    #7 riscv_mmu_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:680:5 (rvvm_x86_64+0xf06f8)
    #8 riscv_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.h:286:5 (rvvm_x86_64+0x139e49)
    #9 riscv_i_sb.llvm.17544518338265111532 /home/lekkit/RVVM/RVVM/src/cpu/riscv_i.c:352:5 (rvvm_x86_64+0x139e49)
    #10 riscv_emulate.llvm.288625106820532266 /home/lekkit/RVVM/RVVM/src/riscv_cpu.c:168:9 (rvvm_x86_64+0xeabca)
    #11 riscv_run_till_event /home/lekkit/RVVM/RVVM/src/riscv_cpu.c (rvvm_x86_64+0xeaaf1)
    #12 riscv_hart_run /home/lekkit/RVVM/RVVM/src/riscv_hart.c:95:9 (rvvm_x86_64+0xee837)
    #13 riscv_hart_run_wrap.llvm.8645139548926494406 /home/lekkit/RVVM/RVVM/src/riscv_hart.c:316:5 (rvvm_x86_64+0xee837)
    #14 __tsan_thread_start_func <null> (rvvm_x86_64+0x5f5f2)

  Location is heap block of size 576 at 0x7b5400000780 allocated by main thread:
    #0 calloc <null> (rvvm_x86_64+0x7e90b)
    #1 safe_calloc /home/lekkit/RVVM/RVVM/src/utils.c:99:17 (rvvm_x86_64+0xf96f0)
    #2 i2c_hid_init /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:349:26 (rvvm_x86_64+0xf96f0)
    #3 i2c_hid_init_auto /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:388:5 (rvvm_x86_64+0xf96f0)
    #4 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #5 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #6 fb_window_init_auto /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:127:21 (rvvm_x86_64+0xf7ced)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:222:14 (rvvm_x86_64+0xe9b09)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xe9b09)

  Thread T1 (tid=191935, running) created by main thread at:
    #0 pthread_create <null> (rvvm_x86_64+0x647f6)
    #1 thread_create /home/lekkit/RVVM/RVVM/src/threading.c:61:13 (rvvm_x86_64+0xee6f9)
    #2 riscv_hart_spawn /home/lekkit/RVVM/RVVM/src/riscv_hart.c:323:18 (rvvm_x86_64+0xee6f9)
    #3 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #4 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #5 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:247:9 (rvvm_x86_64+0xea135)
    #6 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea135)

SUMMARY: ThreadSanitizer: data race /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:106:29 in report_id_queue_insert
==================
==================
WARNING: ThreadSanitizer: data race (pid=191931)
  Write of size 2 at 0x7b54000007a6 by main thread:
    #0 report_id_queue_insert /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c (rvvm_x86_64+0xfa3d6)
    #1 i2c_hid_input_available.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:156:5 (rvvm_x86_64+0xfa3d6)
    #2 hid_mouse_scroll /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:185:5 (rvvm_x86_64+0xf9388)
    #3 fb_window_update /home/lekkit/RVVM/RVVM/src/devices/x11window_xlib.c:362:21 (rvvm_x86_64+0x11c620)
    #4 window_update /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:80:5 (rvvm_x86_64+0xf7dff)
    #5 builtin_eventloop.llvm.889849392825762815 /home/lekkit/RVVM/RVVM/src/rvvm.c:255:21 (rvvm_x86_64+0xf4030)
    #6 rvvm_run_eventloop /home/lekkit/RVVM/RVVM/src/rvvm.c:701:5 (rvvm_x86_64+0xf51a3)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:248:9 (rvvm_x86_64+0xea13a)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea13a)

  Previous write of size 2 at 0x7b54000007a6 by thread T1:
    #0 report_id_queue_remove_at /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:124:22 (rvvm_x86_64+0xfa563)
    #1 i2c_hid_read_report /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:169:9 (rvvm_x86_64+0xfa563)
    #2 i2c_hid_read_reg /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:221:9 (rvvm_x86_64+0xf9f41)
    #3 i2c_hid_read.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:317:13 (rvvm_x86_64+0xf9f41)
    #4 i2c_oc_mmio_write.llvm.12219271496437194821 /home/lekkit/RVVM/RVVM/src/devices/i2c-oc.c:163:32 (rvvm_x86_64+0xfad7e)
    #5 riscv_mmio_scan /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:403:20 (rvvm_x86_64+0xefe06)
    #6 riscv_mmu_op.llvm.11025864126483078052 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:471:13 (rvvm_x86_64+0xefe06)
    #7 riscv_mmu_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:680:5 (rvvm_x86_64+0xf06f8)
    #8 riscv_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.h:286:5 (rvvm_x86_64+0x139e49)
    #9 riscv_i_sb.llvm.17544518338265111532 /home/lekkit/RVVM/RVVM/src/cpu/riscv_i.c:352:5 (rvvm_x86_64+0x139e49)
    #10 riscv_emulate.llvm.288625106820532266 /home/lekkit/RVVM/RVVM/src/riscv_cpu.c:168:9 (rvvm_x86_64+0xeabca)
    #11 riscv_run_till_event /home/lekkit/RVVM/RVVM/src/riscv_cpu.c (rvvm_x86_64+0xeaaf1)
    #12 riscv_hart_run /home/lekkit/RVVM/RVVM/src/riscv_hart.c:95:9 (rvvm_x86_64+0xee837)
    #13 riscv_hart_run_wrap.llvm.8645139548926494406 /home/lekkit/RVVM/RVVM/src/riscv_hart.c:316:5 (rvvm_x86_64+0xee837)
    #14 __tsan_thread_start_func <null> (rvvm_x86_64+0x5f5f2)

  Location is heap block of size 576 at 0x7b5400000780 allocated by main thread:
    #0 calloc <null> (rvvm_x86_64+0x7e90b)
    #1 safe_calloc /home/lekkit/RVVM/RVVM/src/utils.c:99:17 (rvvm_x86_64+0xf96f0)
    #2 i2c_hid_init /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:349:26 (rvvm_x86_64+0xf96f0)
    #3 i2c_hid_init_auto /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:388:5 (rvvm_x86_64+0xf96f0)
    #4 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #5 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #6 fb_window_init_auto /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:127:21 (rvvm_x86_64+0xf7ced)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:222:14 (rvvm_x86_64+0xe9b09)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xe9b09)

  Thread T1 (tid=191935, running) created by main thread at:
    #0 pthread_create <null> (rvvm_x86_64+0x647f6)
    #1 thread_create /home/lekkit/RVVM/RVVM/src/threading.c:61:13 (rvvm_x86_64+0xee6f9)
    #2 riscv_hart_spawn /home/lekkit/RVVM/RVVM/src/riscv_hart.c:323:18 (rvvm_x86_64+0xee6f9)
    #3 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #4 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #5 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:247:9 (rvvm_x86_64+0xea135)
    #6 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea135)

SUMMARY: ThreadSanitizer: data race /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c in report_id_queue_insert
==================
==================
WARNING: ThreadSanitizer: data race (pid=191931)
  Write of size 2 at 0x7b54000007a8 by main thread:
    #0 report_id_queue_insert /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:112:17 (rvvm_x86_64+0xfa3e3)
    #1 i2c_hid_input_available.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:156:5 (rvvm_x86_64+0xfa3e3)
    #2 hid_mouse_scroll /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:185:5 (rvvm_x86_64+0xf9388)
    #3 fb_window_update /home/lekkit/RVVM/RVVM/src/devices/x11window_xlib.c:362:21 (rvvm_x86_64+0x11c620)
    #4 window_update /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:80:5 (rvvm_x86_64+0xf7dff)
    #5 builtin_eventloop.llvm.889849392825762815 /home/lekkit/RVVM/RVVM/src/rvvm.c:255:21 (rvvm_x86_64+0xf4030)
    #6 rvvm_run_eventloop /home/lekkit/RVVM/RVVM/src/rvvm.c:701:5 (rvvm_x86_64+0xf51a3)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:248:9 (rvvm_x86_64+0xea13a)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea13a)

  Previous write of size 2 at 0x7b54000007a8 by thread T1:
    #0 report_id_queue_remove_at /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:125:43 (rvvm_x86_64+0xfa575)
    #1 i2c_hid_read_report /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:169:9 (rvvm_x86_64+0xfa575)
    #2 i2c_hid_read_reg /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:221:9 (rvvm_x86_64+0xf9f41)
    #3 i2c_hid_read.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:317:13 (rvvm_x86_64+0xf9f41)
    #4 i2c_oc_mmio_write.llvm.12219271496437194821 /home/lekkit/RVVM/RVVM/src/devices/i2c-oc.c:163:32 (rvvm_x86_64+0xfad7e)
    #5 riscv_mmio_scan /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:403:20 (rvvm_x86_64+0xefe06)
    #6 riscv_mmu_op.llvm.11025864126483078052 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:471:13 (rvvm_x86_64+0xefe06)
    #7 riscv_mmu_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:680:5 (rvvm_x86_64+0xf06f8)
    #8 riscv_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.h:286:5 (rvvm_x86_64+0x139e49)
    #9 riscv_i_sb.llvm.17544518338265111532 /home/lekkit/RVVM/RVVM/src/cpu/riscv_i.c:352:5 (rvvm_x86_64+0x139e49)
    #10 riscv_emulate.llvm.288625106820532266 /home/lekkit/RVVM/RVVM/src/riscv_cpu.c:168:9 (rvvm_x86_64+0xeabca)
    #11 riscv_run_till_event /home/lekkit/RVVM/RVVM/src/riscv_cpu.c (rvvm_x86_64+0xeaaf1)
    #12 riscv_hart_run /home/lekkit/RVVM/RVVM/src/riscv_hart.c:95:9 (rvvm_x86_64+0xee837)
    #13 riscv_hart_run_wrap.llvm.8645139548926494406 /home/lekkit/RVVM/RVVM/src/riscv_hart.c:316:5 (rvvm_x86_64+0xee837)
    #14 __tsan_thread_start_func <null> (rvvm_x86_64+0x5f5f2)

  Location is heap block of size 576 at 0x7b5400000780 allocated by main thread:
    #0 calloc <null> (rvvm_x86_64+0x7e90b)
    #1 safe_calloc /home/lekkit/RVVM/RVVM/src/utils.c:99:17 (rvvm_x86_64+0xf96f0)
    #2 i2c_hid_init /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:349:26 (rvvm_x86_64+0xf96f0)
    #3 i2c_hid_init_auto /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:388:5 (rvvm_x86_64+0xf96f0)
    #4 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #5 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #6 fb_window_init_auto /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:127:21 (rvvm_x86_64+0xf7ced)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:222:14 (rvvm_x86_64+0xe9b09)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xe9b09)

  Thread T1 (tid=191935, running) created by main thread at:
    #0 pthread_create <null> (rvvm_x86_64+0x647f6)
    #1 thread_create /home/lekkit/RVVM/RVVM/src/threading.c:61:13 (rvvm_x86_64+0xee6f9)
    #2 riscv_hart_spawn /home/lekkit/RVVM/RVVM/src/riscv_hart.c:323:18 (rvvm_x86_64+0xee6f9)
    #3 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #4 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #5 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:247:9 (rvvm_x86_64+0xea135)
    #6 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea135)

SUMMARY: ThreadSanitizer: data race /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:112:17 in report_id_queue_insert
==================
==================
WARNING: ThreadSanitizer: data race (pid=191931)
  Read of size 2 at 0x7b54000007a6 by main thread:
    #0 report_id_queue_insert /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:108:16 (rvvm_x86_64+0xfa3c0)
    #1 i2c_hid_input_available.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:156:5 (rvvm_x86_64+0xfa3c0)
    #2 hid_mouse_scroll /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:185:5 (rvvm_x86_64+0xf9388)
    #3 fb_window_update /home/lekkit/RVVM/RVVM/src/devices/x11window_xlib.c:362:21 (rvvm_x86_64+0x11c620)
    #4 window_update /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:80:5 (rvvm_x86_64+0xf7dff)
    #5 builtin_eventloop.llvm.889849392825762815 /home/lekkit/RVVM/RVVM/src/rvvm.c:255:21 (rvvm_x86_64+0xf4030)
    #6 rvvm_run_eventloop /home/lekkit/RVVM/RVVM/src/rvvm.c:701:5 (rvvm_x86_64+0xf51a3)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:248:9 (rvvm_x86_64+0xea13a)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea13a)

  Previous write of size 2 at 0x7b54000007a6 by thread T1:
    #0 report_id_queue_remove_at /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:124:22 (rvvm_x86_64+0xfa563)
    #1 i2c_hid_read_report /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:169:9 (rvvm_x86_64+0xfa563)
    #2 i2c_hid_read_reg /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:221:9 (rvvm_x86_64+0xf9f41)
    #3 i2c_hid_read.llvm.1433193341291022662 /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:317:13 (rvvm_x86_64+0xf9f41)
    #4 i2c_oc_mmio_write.llvm.12219271496437194821 /home/lekkit/RVVM/RVVM/src/devices/i2c-oc.c:163:32 (rvvm_x86_64+0xfad7e)
    #5 riscv_mmio_scan /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:403:20 (rvvm_x86_64+0xefe06)
    #6 riscv_mmu_op.llvm.11025864126483078052 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:471:13 (rvvm_x86_64+0xefe06)
    #7 riscv_mmu_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.c:680:5 (rvvm_x86_64+0xf06f8)
    #8 riscv_store_u8 /home/lekkit/RVVM/RVVM/src/riscv_mmu.h:286:5 (rvvm_x86_64+0x139e49)
    #9 riscv_i_sb.llvm.17544518338265111532 /home/lekkit/RVVM/RVVM/src/cpu/riscv_i.c:352:5 (rvvm_x86_64+0x139e49)
    #10 riscv_emulate.llvm.288625106820532266 /home/lekkit/RVVM/RVVM/src/riscv_cpu.c:168:9 (rvvm_x86_64+0xeabca)
    #11 riscv_run_till_event /home/lekkit/RVVM/RVVM/src/riscv_cpu.c (rvvm_x86_64+0xeaaf1)
    #12 riscv_hart_run /home/lekkit/RVVM/RVVM/src/riscv_hart.c:95:9 (rvvm_x86_64+0xee837)
    #13 riscv_hart_run_wrap.llvm.8645139548926494406 /home/lekkit/RVVM/RVVM/src/riscv_hart.c:316:5 (rvvm_x86_64+0xee837)
    #14 __tsan_thread_start_func <null> (rvvm_x86_64+0x5f5f2)

  Location is heap block of size 576 at 0x7b5400000780 allocated by main thread:
    #0 calloc <null> (rvvm_x86_64+0x7e90b)
    #1 safe_calloc /home/lekkit/RVVM/RVVM/src/utils.c:99:17 (rvvm_x86_64+0xf96f0)
    #2 i2c_hid_init /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:349:26 (rvvm_x86_64+0xf96f0)
    #3 i2c_hid_init_auto /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:388:5 (rvvm_x86_64+0xf96f0)
    #4 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #5 hid_mouse_init_auto /home/lekkit/RVVM/RVVM/src/devices/hid-mouse.c:160:5 (rvvm_x86_64+0xf8e72)
    #6 fb_window_init_auto /home/lekkit/RVVM/RVVM/src/devices/fb_window.c:127:21 (rvvm_x86_64+0xf7ced)
    #7 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:222:14 (rvvm_x86_64+0xe9b09)
    #8 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xe9b09)

  Thread T1 (tid=191935, running) created by main thread at:
    #0 pthread_create <null> (rvvm_x86_64+0x647f6)
    #1 thread_create /home/lekkit/RVVM/RVVM/src/threading.c:61:13 (rvvm_x86_64+0xee6f9)
    #2 riscv_hart_spawn /home/lekkit/RVVM/RVVM/src/riscv_hart.c:323:18 (rvvm_x86_64+0xee6f9)
    #3 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #4 rvvm_start_machine /home/lekkit/RVVM/RVVM/src/rvvm.c:520:9 (rvvm_x86_64+0xf32fd)
    #5 rvvm_main /home/lekkit/RVVM/RVVM/src/main.c:247:9 (rvvm_x86_64+0xea135)
    #6 main /home/lekkit/RVVM/RVVM/src/main.c:276:15 (rvvm_x86_64+0xea135)

SUMMARY: ThreadSanitizer: data race /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:108:16 in report_id_queue_insert
```

</details>

I'm not forcing you to fix these, just tell me if you don't want to. I can do it myself, but I'm surprized there are so much (There are some duplicates)

**Comment by X547** [comment]
> SUMMARY: ThreadSanitizer: data race /home/lekkit/RVVM/RVVM/src/devices/i2c-hid.c:155:18 in i2c_hid_input_available.llvm.1433193341291022662

Added missing lock.

**Comment by LekKit** [comment]
Good. I approve this so far.
Last tiny change to `i2c_hid.c@171` to shut off GCC warnings about possible overflow (I assume shouldn't happen?):
`if (report_type == REPORT_TYPE_INPUT && offset == (uint32_t)(i2c_hid->report_size - 1)) {`

**Comment by X547** [comment]
This change do not implement following hooks in I2C HID controller:
* `get_idle`
* `set_idle`
* `get_protocol`
* `set_protocol`
* `set_power`

Implemented HID devices currently do not use this hooks.

**Comment by LekKit** [comment]
> This change do not implement following hooks in I2C HID controller:
> 
>     * `get_idle`
> 
>     * `set_idle`
> 
>     * `get_protocol`
> 
>     * `set_protocol`
> 
>     * `set_power`
> 
> 
> Implemented HID devices currently do not use this hooks.

Fine unless they are unconditionally called somewhere

**Comment by X547** [comment]
> Last tiny change to `i2c_hid.c@171` to shut off GCC warnings about possible overflow (I assume shouldn't happen?):

Do you mean underflow when `i2c_hid->report_size == 0`? In theory it can happen if HID device will return zero read report size.

**Comment by X547** [comment]
> Last tiny change to `i2c_hid.c@171` to shut off GCC warnings about possible overflow (I assume shouldn't happen?):

Fixed.

**Review by LekKit — APPROVED** [review]
We're good to go, thanks very much for this!

**Comment by LekKit** [comment]
Tiny nuisance: SMP Linux guest spend a lot of time (~10s) in I2C HID reset, needs investigation

**Comment by LekKit** [comment]
> Tiny nuisance: SMP Linux guest spend a lot of time (~10s) in I2C HID reset, needs investigation

Fixed by 44fcc7b.
